### ISSUE TITLE
Compiling help: [BRIEF DESCRIPTION / ERROR MESSAGE OUTPUT]

### ISSUE THREAD

**Issue by GIDRO32** [magnumsrt/MagEngine-Public#35]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Windows

## When I try to compile the game, this happens, I tried to install polymod 1.3.0, but it didn't help

C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
                                         C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
                                                                                 C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
 C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                            C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : ... For function argument 'e'
                                                           C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                                                                                       C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : ... For function argument 'e'
                                                                                                                       C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                           C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : ... For function argument 'e'
                                                           C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                                                                                       C:/HaxeToolkit/haxe/lib/polymod/1,6,0/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : ... For function argument 'e'
                                                                                                                       source/PlayState.hx:2190: characters 16-28 : Type not found : VideoHandler

PS C:\Users\Admin\Downloads\MagEngine-Public-main\MagEngine-Public-main>

**Comment by TheKitBoi** [comment]
1.haxelib remove polymod

2.haxelib git polymod https://github.com/larsiusprime/polymod.git

3.haxelib git hxCodec https://github.com/polybiusproxy/hxCodec

**Comment by GIDRO32** [comment]
I did all three, but it seems to me that I still have the same problem
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
                                       C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
                                                                             C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
                                                                                                                   C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                    C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : ... For function argument 'e'
                                                 C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                                                                           C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : ... For function argument 'e'
                                                                                                         C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
                           C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : ... For function argument 'e'
                                         C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                                                                   C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : ... For function argument 'e'
                                                                                                 source/PlayState.hx:2190: characters 16-28 : Type not found : VideoHandler

**Comment by magnumsrt** [comment]
This is completely my fault, I forgot to commit the updated project.xml. Reinstalling the updated source code should fix the problem.
I'll keep this open until resolved, let me know if this helps.

**Comment by GIDRO32** [comment]
Unfortunately, it didn't help, now it looks like this
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:366: characters 69-73 : polymod.hscript._internal.ErrorEx has no field line
                                       C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:60: characters 52-56 : polymod.hscript._internal.ErrorEx has no field line
                                                                             C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodScriptClass.hx:63: characters 87-91 : polymod.hscript._internal.ErrorEx has no field line
                                                                                                                   C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                    C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:73: characters 14-43 : ... For function argument 'e'
                                                 C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                                                                           C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:450: characters 13-38 : ... For function argument 'e'
                                                                                                         C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : polymod.hscript._internal.ErrorEx should be hscript.Error
                           C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:105: characters 13-40 : ... For function argument 'e'
                                         C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : polymod.hscript._internal.ErrorEx should be hscript.Error
                                                                                   C:/HaxeToolkit/haxe/lib/polymod/git/polymod/hscript/_internal/PolymodInterpEx.hx:483: characters 13-38 : ... For function argument 'e'

**Comment by magnumsrt** [comment]
Try installing polymod version 1.3.0 from **haxelib** directly (Not Git). I've never seen anything like this before.

**Comment by GIDRO32** [comment]
YES! It works! Thank you!
