### ISSUE TITLE
Game Crash When Pressing 7 To Enter The Chart Editor(Mag Engine 1.5.5)

### ISSUE THREAD

**Issue by Zyflx** [Magnumsrt/MagEngine-Public#38]
![image_2023-03-10_164742398](https://user-images.githubusercontent.com/100444522/224434660-d12ad412-7535-4f44-be67-a6e8cbc9d659.png)

**Comment by Magnumsrt** [comment]
fixed, you may need to wait a little for the gamebanana files to be reposted as their file servers are garbage, meanwhile you can go to the actions builds on this github page and get them right when they are finished building.

Thanks for posting the issue!
